name: Actualizar GeoJSON desde Google Sheets

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pandas pyproj

      - name: Generar GeoJSON
        run: python update_geojson.py

      - name: Commit & push si hay cambios
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add docs/dictamenes.geojson
          git commit -m "Actualizar GeoJSON automático" || echo "Sin cambios para commitear"
          git push

